apiVersion: apps/v1
   kind: Deployment
   metadata:
     name: flask-app
   spec:
     replicas: 2
     selector:
       matchLabels:
         app: flask-app
     template:
       metadata:
         labels:
           app: flask-app
       spec:
         containers:
         - name: flask-app
           image: flask-app:latest
           ports:
           - containerPort: 8080
           env:
           - name: SECRET_KEY
             valueFrom:
               secretKeyRef:
                 name: flask-secrets
                 key: secret-key
           - name: DATABASE_URL
             valueFrom:
               secretKeyRef:
                 name: flask-secrets
                 key: database-url
   ---
   apiVersion: v1
   kind: Service
   metadata:
     name: flask-app-service
   spec:
     selector:
       app: flask-app
     ports:
     - protocol: TCP
       port: 80
       targetPort: 8080
     type: LoadBalancer
